name: Image Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

env:
  IMAGE_PREFIX: ghcr.io/thehonker/weechat
  PLATFORMS: linux/amd64,linux/arm64
  ARCHS: amd64,arm64
  VERSION: latest

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker - Alpine
        id: meta-alpine
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=latest,priority=1000
            type=schedule,enable=true,priority=900,pattern={{date 'YYYYMMDD'}}
          images: |
            ${{ env.IMAGE_PREFIX }}-alpine

      - name: Build and push Docker image - Alpine
        id: build-alpine
        uses: docker/build-push-action@v6
        with:
          context: alpine/
          pull: true
          file: alpine/Containerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta-alpine.outputs.tags }}
          labels: ${{ steps.meta-alpine.outputs.labels }}
          cache-from: type=local,src=/home/runner/.${{ env.IMAGE_PREFIX }}.buildx-cache
          cache-to: type=local,dest=/home/runner/.${{ env.IMAGE_PREFIX }}.buildx-cache

      - name: Extract metadata (tags, labels) for Docker - Debian
        id: meta-debian
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=latest,priority=1000
            type=schedule,enable=true,priority=900,pattern={{date 'YYYYMMDD'}}
          images: |
            ${{ env.IMAGE_PREFIX }}-debian
  
      - name: Build and push Docker image - Debian
        id: build-debian
        uses: docker/build-push-action@v6
        with:
          context: debian/
          pull: true
          file: debian/Containerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta-debian.outputs.tags }}
          labels: ${{ steps.meta-debian.outputs.labels }}
          cache-from: type=local,src=/home/runner/.${{ env.IMAGE_PREFIX }}.buildx-cache
          cache-to: type=local,dest=/home/runner/.${{ env.IMAGE_PREFIX }}.buildx-cache
  